class GPTTextData:
    """
    This class is for storing the info of the text generated by ChatGPT
    """

    id = ""
    text = ""
    inEnglish=""
    pseudoLabel=""
    label=""

    def __init__(self, id, text):
        self.id = id
        self.text = text

    def __init__(self, id, text, label, pseudoLabel):
        self.id = id
        self.text = text
        self.label = label
        self.pseudoLabel = pseudoLabel

    def __str__(self):
        return str(self.id) + " | " + self.text + " | " + self.inEnglish + " | " + self.pseudoLabel + " | " + self.label