# ChatGPT generated dataset

DIR_OUTPUT = "output/"
FILE_NOSAMPLING_CHATGPT_TEXT_DATASET = DIR_OUTPUT + "Dataset_ChatGPT_txt_nos.obj"

NUM_CLASSES = 6

# Sampling size
SAMPLING_400 = 400
SAMPLING_800 = 800
SAMPLING_1200 = 1200
SAMPLING_1600 = 1600
SAMPLING_2000 = 2000
SAMPLING_2400 = 2400
SAMPLING_2800 = 2800
SAMPLING_3200 = 3200
SAMPLING_3600 = 3600

# Emotion
EMOTION_LABEL_NEUTRAL_CODE = 0
EMOTION_LABEL_HAPPY_CODE = 1
EMOTION_LABEL_FEAR_CODE = 2
EMOTION_LABEL_SURPRISE_CODE = 3
EMOTION_LABEL_ANGRY_CODE = 4
EMOTION_LABEL_SAD_CODE = 5

EMOTION_LABEL_NEUTRAL = 'Neutral'
EMOTION_LABEL_HAPPY = 'Happy'
EMOTION_LABEL_FEAR = 'Fear'
EMOTION_LABEL_SURPRISE = 'Surprise'
EMOTION_LABEL_ANGRY = 'Angry'
EMOTION_LABEL_SAD = 'Sad'

Label_Desc_Code = {
    EMOTION_LABEL_NEUTRAL: EMOTION_LABEL_NEUTRAL_CODE,
    EMOTION_LABEL_HAPPY: EMOTION_LABEL_HAPPY_CODE,
    EMOTION_LABEL_FEAR: EMOTION_LABEL_FEAR_CODE,
    EMOTION_LABEL_SURPRISE: EMOTION_LABEL_SURPRISE_CODE,
    EMOTION_LABEL_ANGRY: EMOTION_LABEL_ANGRY_CODE,
    EMOTION_LABEL_SAD: EMOTION_LABEL_SAD_CODE
}

Label_Code_Desc = {
    EMOTION_LABEL_NEUTRAL_CODE: EMOTION_LABEL_NEUTRAL,
    EMOTION_LABEL_HAPPY_CODE: EMOTION_LABEL_HAPPY,
    EMOTION_LABEL_FEAR_CODE: EMOTION_LABEL_FEAR,
    EMOTION_LABEL_SURPRISE_CODE: EMOTION_LABEL_SURPRISE,
    EMOTION_LABEL_ANGRY_CODE: EMOTION_LABEL_ANGRY,
    EMOTION_LABEL_SAD_CODE: EMOTION_LABEL_SAD
}

# File Names
FILE_CHATGPT_DF = DIR_OUTPUT + "DataFrame_chatgpt_resampling_"

FILE_TRAINING_ENG_NOS = DIR_OUTPUT + "DataFrame_training_eng_nos_"
FILE_TRAINING_MUL_NOS = DIR_OUTPUT + "DataFrame_training_multi_nos_"